apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: nginx
      {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: nginx-data
              mountPath: /usr/share/nginx/html
            {{- end }}
            {{- if .Values.secret.enabled }}
            - name: nginx-secret
              mountPath: /etc/nginx/secret
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx
        {{- end }}
        {{- if .Values.secret.enabled }}
        - name: nginx-secret
          secret:
            secretName: nginx
        {{- end }}
