apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: {{ .Values.pv.size | default "1Gi" }}
  accessModes:
    - {{ .Values.pv.accessMode | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.hostPath | default "/mnt/data/nginx" }} 