apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  username: {{ .Values.secret.username | default "" | b64enc | quote }}
  password: {{ .Values.secret.password | default "" | b64enc | quote }}